# 本次服务网关不集成配置中心
server:
  port: 20004

spring:
  application:
    name: platform-gateway
  main:
    # 允许Bean名称相同时进行Bean覆盖 => 用于保证多个Bean注入时项目可正常启动(防止没配置@Primary注解)
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.1.150
    port: 6379
    database: 0
    #password: root
  cloud:
    gateway:
      globalcors:
        # 配置跨域支持
        cors-configurations:
          '[/**]':
            # 允许返回的资源可以共享给请求来源
            allowed-origins:
#            - "http://localhost:8080"
#            - "http://shop.z.mukewang.com:8080"
#            - "http://center.z.mukewang.com:8080"
#            - "http://shop.z.mukewang.com"
#            - "http://center.z.mukewang.com"
#            - "http://192.168.1.102:8080"
            - "*"
            # 允许请求带上认证信息, 比如cookie、authorization
            allow-credentials: true
            # 允许接收请求所有的Header
            allowed-headers: "*"
            # 允许接收所有请求的方法
            allowed-methods: "*"
            # 允许响应时带上所有Header
            expose-headers: "*"
            # 表示浏览器跨域预检指令Options可以在浏览器缓存多长时间, 秒为单位
            max-age: 600
      discovery:
        locator:
          # 生产上需要关闭自动配置节点路由规则
          enabled: false
          lower-case-service-id: true
      # 这里在Java配置类里配置路由规则
      # routes:

# Eureka注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.150:20000/eureka/
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: 192.168.1.150
    prefer-ip-address: true

# 开启所有Actuator的Endpoints
management:
  # 已禁用, 可不配
#  security:
#    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always