server:
  port: 10006

spring:
  application:
    name: foodie-auth-service
  redis:
    database: 0
    host: 192.168.1.150
    port: 6379
    #password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.150:20000/eureka/
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: 192.168.1.150
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
